language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
before_install:
  - sudo apt-get install gfortran libopenblas-dev liblapack-dev
  - pip install poetry
install:
  - poetry install
script:
  - poetry run flake8
  - poetry run pytest
